steps:
- id: "Building image from Dockerfile.prod"
  name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/mfc3-subscription:$SHORT_SHA',
   '-t', 
   'gcr.io/$PROJECT_ID/mfc3-subscription:latest',
   '.'
  ]

#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ecommerce'
  
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'subscription', 
   'subscription=gcr.io/$PROJECT_ID/mfc3-subscription:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ecommerce'

# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/mfc3-subscription:$TAG_NAME',
   'gcr.io/$PROJECT_ID/mfc3-subscription:latest'
  ]  